### ISSUE TITLE
SecurityDefinition as header cannot be specified in build.gradle

### ISSUE THREAD

**Issue by fmotrifork** [gigaSproule/swagger-gradle-plugin#41]
I would love to use the "simple" way of defining a securityDefinition in my build.gradle file:
```
securityDefinition {
    name = 'MyBasicAuth'
    type = 'basic'
}
```

My security demands a JWT token set as a header with name=Authorization.

In Json i can define this like this:

`{"jwt": { "type": "apiKey", "name": "Authorization", "in": "header" }}`

This is not possible in the gradle syntax used now. As the "key" called "name" is used for the name of the entire securitySchemes and I need to set a name for the header aswell.

```
securityDefinition {
    name = 'jwt'
    name..?? = 'Authorization'
    type = 'apiKey'
    keyLocation = 'header'
}
```

In swagger YAML this would look like this:

```
components:
  securitySchemes:
    jwt:
      type: apiKey
      in: header
      name: Authorization
```
